blank_issues_enabled: true
contact_links:
  - name: General Support/Question
    url: https://discord.gg/RQQkdZQwEJ
    about: Please visit our Discord community for most general support or questions.
